// Generated by commsdsl2comms v5.0.1

/// @file
/// @brief Contains definition of protocol bare metal default options.

#pragma once

#include "oac_msg/options/DefaultOptions.h"

#ifndef DEFAULT_SEQ_FIXED_STORAGE_SIZE
/// @brief Define default fixed size for various sequence fields
/// @details May be defined during compile time to change the default value.
#define DEFAULT_SEQ_FIXED_STORAGE_SIZE 32
#endif

namespace oac_msg
{

namespace options
{

/// @brief Default bare metal options of the protocol.
template <typename TBase = oac_msg::options::DefaultOptions>
struct BareMetalDefaultOptionsT : public TBase
{
    /// @brief Extra options for fields.
    struct field : public TBase::field
    {
        struct RTPExtensionMembers : public TBase::field::RTPExtensionMembers
        {
            struct GenericMembers : public TBase::field::RTPExtensionMembers::GenericMembers
            {
                /// @brief Extra options for @ref
                ///     oac_msg::field::RTPExtensionMembers::GenericMembers::Content
                ///     field.
                using Content =
                    std::tuple<
                        comms::option::app::FixedSizeStorage<DEFAULT_SEQ_FIXED_STORAGE_SIZE>,
                        typename TBase::field::RTPExtensionMembers::GenericMembers::Content
                    >;
            }; // struct GenericMembers

            struct Oac_extensionMembers : public TBase::field::RTPExtensionMembers::Oac_extensionMembers
            {
                /// @brief Extra options for @ref
                ///     oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Dntp_server_ipv4_address
                ///     field.
                using Dntp_server_ipv4_address =
                    std::tuple<
                        comms::option::app::SequenceFixedSizeUseFixedSizeStorage,
                        typename TBase::field::RTPExtensionMembers::Oac_extensionMembers::Dntp_server_ipv4_address
                    >;
            }; // struct Oac_extensionMembers
        }; // struct RTPExtensionMembers
    }; // struct field

    /// @brief Extra options for messages.
    struct message : public TBase::message
    {
        /// @brief Extra options for fields of
        ///     @ref oac_msg::message::RTPMessage message.
        struct RTPMessageFields : public TBase::message::RTPMessageFields
        {
            /// @brief Extra options for @ref
            ///     oac_msg::message::RTPMessageFields::Content
            ///     field.
            using Content =
                std::tuple<
                    comms::option::app::FixedSizeStorage<DEFAULT_SEQ_FIXED_STORAGE_SIZE>,
                    typename TBase::message::RTPMessageFields::Content
                >;
        };
    }; // struct message

    /// @brief Extra options for frames.
    struct frame : public TBase::frame
    {
        /// @brief Extra options for layers of
        ///     @ref oac_msg::frame::Frame frame.
        struct FrameLayers : public TBase::frame::FrameLayers
        {
            /// @brief Extra options for @ref
            ///     oac_msg::frame::FrameLayers::Data layer.
            using Data =
                std::tuple<
                    comms::option::app::FixedSizeStorage<DEFAULT_SEQ_FIXED_STORAGE_SIZE * 8>,
                    typename TBase::frame::FrameLayers::Data
                >;
        }; // struct FrameLayers
    }; // struct frame
};

/// @brief Alias to @ref BareMetalDefaultOptionsT with default template parameter.
using BareMetalDefaultOptions = BareMetalDefaultOptionsT<>;

} // namespace options

} // namespace oac_msg
