// Generated by commsdsl2comms v5.0.1

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref dntp_msg::field::Message field.

#pragma once

#include <cstdint>
#include "dntp_msg/field/TimestampCommon.h"

namespace dntp_msg
{

namespace field
{

/// @brief Scope for all the common definitions of the member fields of
///     @ref dntp_msg::field::Message field.
struct MessageMembersCommon
{
    /// @brief Common types and functions for
    ///     @ref dntp_msg::field::MessageMembers::Version field.
    struct VersionCommon
    {
        /// @brief Re-definition of the value type used by
        ///     dntp_msg::field::MessageMembers::Version field.
        using ValueType = std::uint8_t;

        /// @brief Name of the @ref dntp_msg::field::MessageMembers::Version field.
        static const char* name()
        {
            return "version";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Common definitions of the member fields of
    ///     @ref dntp_msg::field::MessageMembers::Originate_timestamp field.
    using Originate_timestampMembersCommon = dntp_msg::field::TimestampMembersCommon;

    /// @brief Common types and functions for
    ///     @ref dntp_msg::field::MessageMembers::Originate_timestamp field.
    struct Originate_timestampCommon : public dntp_msg::field::TimestampCommon
    {
        /// @brief Name of the @ref dntp_msg::field::MessageMembers::Originate_timestamp field.
        static const char* name()
        {
            return "originate_timestamp";
        }
    };

    /// @brief Common definitions of the member fields of
    ///     @ref dntp_msg::field::MessageMembers::Receive_timestamp field.
    using Receive_timestampMembersCommon = dntp_msg::field::TimestampMembersCommon;

    /// @brief Common types and functions for
    ///     @ref dntp_msg::field::MessageMembers::Receive_timestamp field.
    struct Receive_timestampCommon : public dntp_msg::field::TimestampCommon
    {
        /// @brief Name of the @ref dntp_msg::field::MessageMembers::Receive_timestamp field.
        static const char* name()
        {
            return "receive_timestamp";
        }
    };

    /// @brief Common definitions of the member fields of
    ///     @ref dntp_msg::field::MessageMembers::Transmit_timestamp field.
    using Transmit_timestampMembersCommon = dntp_msg::field::TimestampMembersCommon;

    /// @brief Common types and functions for
    ///     @ref dntp_msg::field::MessageMembers::Transmit_timestamp field.
    struct Transmit_timestampCommon : public dntp_msg::field::TimestampCommon
    {
        /// @brief Name of the @ref dntp_msg::field::MessageMembers::Transmit_timestamp field.
        static const char* name()
        {
            return "transmit_timestamp";
        }
    };
};

/// @brief Common types and functions for
///     @ref dntp_msg::field::Message field.
struct MessageCommon
{
    /// @brief Name of the @ref dntp_msg::field::Message field.
    static const char* name()
    {
        return "Message";
    }
};

} // namespace field

} // namespace dntp_msg
