language: cpp
os:
  - linux
  - osx
  #- windows  # ATM only visual studio 2017 is available. 2019 is required

script:
  - mkdir build && cd build
  - cmake -Dopenac_enable_juce_tests=OFF ..
  - cmake --build .
  - ctest -C Debug
