// Generated by commsdsl2comms v5.0.1

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref oac_msg::field::RTPExtension field.

#pragma once

#include <cstdint>
#include "oac_msg/field/TimestampCommon.h"

namespace oac_msg
{

namespace field
{

/// @brief Scope for all the common definitions of the member fields of
///     @ref oac_msg::field::RTPExtension field.
struct RTPExtensionMembersCommon
{
    /// @brief Scope for all the common definitions of the member fields of
    ///     @ref oac_msg::field::RTPExtensionMembers::Generic field.
    struct GenericMembersCommon
    {
        /// @brief Common types and functions for
        ///     @ref oac_msg::field::RTPExtensionMembers::GenericMembers::Extension_id field.
        struct Extension_idCommon
        {
            /// @brief Re-definition of the value type used by
            ///     oac_msg::field::RTPExtensionMembers::GenericMembers::Extension_id field.
            using ValueType = std::uint16_t;

            /// @brief Name of the @ref oac_msg::field::RTPExtensionMembers::GenericMembers::Extension_id field.
            static const char* name()
            {
                return "extension_id";
            }

            /// @brief Compile time detection of special values presence.
            static constexpr bool hasSpecials()
            {
                return false;
            }
        };

        /// @brief Common types and functions for
        ///     @ref oac_msg::field::RTPExtensionMembers::GenericMembers::Length field.
        struct LengthCommon
        {
            /// @brief Re-definition of the value type used by
            ///     oac_msg::field::RTPExtensionMembers::GenericMembers::Length field.
            using ValueType = std::uint16_t;

            /// @brief Name of the @ref oac_msg::field::RTPExtensionMembers::GenericMembers::Length field.
            static const char* name()
            {
                return "length";
            }

            /// @brief Compile time detection of special values presence.
            static constexpr bool hasSpecials()
            {
                return false;
            }
        };

        /// @brief Scope for all the common definitions of the member fields of
        ///     @ref oac_msg::field::RTPExtensionMembers::GenericMembers::Content field.
        struct ContentMembersCommon
        {
            /// @brief Common types and functions for
            ///     @ref oac_msg::field::RTPExtensionMembers::GenericMembers::ContentMembers::Element field.
            struct ElementCommon
            {
                /// @brief Re-definition of the value type used by
                ///     oac_msg::field::RTPExtensionMembers::GenericMembers::ContentMembers::Element field.
                using ValueType = std::uint32_t;

                /// @brief Name of the @ref oac_msg::field::RTPExtensionMembers::GenericMembers::ContentMembers::Element field.
                static const char* name()
                {
                    return "element";
                }

                /// @brief Compile time detection of special values presence.
                static constexpr bool hasSpecials()
                {
                    return false;
                }
            };
        };

        /// @brief Common types and functions for
        ///     @ref oac_msg::field::RTPExtensionMembers::GenericMembers::Content field.
        struct ContentCommon
        {
            /// @brief Name of the @ref oac_msg::field::RTPExtensionMembers::GenericMembers::Content field.
            static const char* name()
            {
                return "content";
            }
        };
    };

    /// @brief Common types and functions for
    ///     @ref oac_msg::field::RTPExtensionMembers::Generic field.
    struct GenericCommon
    {
        /// @brief Name of the @ref oac_msg::field::RTPExtensionMembers::Generic field.
        static const char* name()
        {
            return "generic";
        }
    };

    /// @brief Scope for all the common definitions of the member fields of
    ///     @ref oac_msg::field::RTPExtensionMembers::Oac_extension field.
    struct Oac_extensionMembersCommon
    {
        /// @brief Common types and functions for
        ///     @ref oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Extension_id field.
        struct Extension_idCommon
        {
            /// @brief Re-definition of the value type used by
            ///     oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Extension_id field.
            using ValueType = std::uint16_t;

            /// @brief Name of the @ref oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Extension_id field.
            static const char* name()
            {
                return "extension_id";
            }

            /// @brief Compile time detection of special values presence.
            static constexpr bool hasSpecials()
            {
                return false;
            }
        };

        /// @brief Common types and functions for
        ///     @ref oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Length field.
        struct LengthCommon
        {
            /// @brief Re-definition of the value type used by
            ///     oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Length field.
            using ValueType = std::uint16_t;

            /// @brief Name of the @ref oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Length field.
            static const char* name()
            {
                return "length";
            }

            /// @brief Compile time detection of special values presence.
            static constexpr bool hasSpecials()
            {
                return false;
            }
        };

        /// @brief Common types and functions for
        ///     @ref oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Version field.
        struct VersionCommon
        {
            /// @brief Re-definition of the value type used by
            ///     oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Version field.
            using ValueType = std::uint16_t;

            /// @brief Name of the @ref oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Version field.
            static const char* name()
            {
                return "version";
            }

            /// @brief Compile time detection of special values presence.
            static constexpr bool hasSpecials()
            {
                return false;
            }
        };

        /// @brief Common types and functions for
        ///     @ref oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Dntp_server_port field.
        struct Dntp_server_portCommon
        {
            /// @brief Re-definition of the value type used by
            ///     oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Dntp_server_port field.
            using ValueType = std::uint16_t;

            /// @brief Name of the @ref oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Dntp_server_port field.
            static const char* name()
            {
                return "dntp_server_port";
            }

            /// @brief Compile time detection of special values presence.
            static constexpr bool hasSpecials()
            {
                return false;
            }
        };

        /// @brief Scope for all the common definitions of the member fields of
        ///     @ref oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Dntp_server_ipv4_address field.
        struct Dntp_server_ipv4_addressMembersCommon
        {
            /// @brief Common types and functions for
            ///     @ref oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Dntp_server_ipv4_addressMembers::Element field.
            struct ElementCommon
            {
                /// @brief Re-definition of the value type used by
                ///     oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Dntp_server_ipv4_addressMembers::Element field.
                using ValueType = std::uint8_t;

                /// @brief Name of the @ref oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Dntp_server_ipv4_addressMembers::Element field.
                static const char* name()
                {
                    return "element";
                }

                /// @brief Compile time detection of special values presence.
                static constexpr bool hasSpecials()
                {
                    return false;
                }
            };
        };

        /// @brief Common types and functions for
        ///     @ref oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Dntp_server_ipv4_address field.
        struct Dntp_server_ipv4_addressCommon
        {
            /// @brief Name of the @ref oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Dntp_server_ipv4_address field.
            static const char* name()
            {
                return "dntp_server_ipv4_address";
            }
        };

        /// @brief Common definitions of the member fields of
        ///     @ref oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Reference_timestamp field.
        using Reference_timestampMembersCommon = oac_msg::field::TimestampMembersCommon;

        /// @brief Common types and functions for
        ///     @ref oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Reference_timestamp field.
        struct Reference_timestampCommon : public oac_msg::field::TimestampCommon
        {
            /// @brief Name of the @ref oac_msg::field::RTPExtensionMembers::Oac_extensionMembers::Reference_timestamp field.
            static const char* name()
            {
                return "reference_timestamp";
            }
        };
    };

    /// @brief Common types and functions for
    ///     @ref oac_msg::field::RTPExtensionMembers::Oac_extension field.
    struct Oac_extensionCommon
    {
        /// @brief Name of the @ref oac_msg::field::RTPExtensionMembers::Oac_extension field.
        static const char* name()
        {
            return "oac_extension";
        }
    };
};

/// @brief Common types and functions for
///     @ref oac_msg::field::RTPExtension field.
struct RTPExtensionCommon
{
    /// @brief Name of the @ref oac_msg::field::RTPExtension field.
    static const char* name()
    {
        return "RTPExtension";
    }
};

} // namespace field

} // namespace oac_msg
