// Generated by commsdsl2comms v5.0.1

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref oac_msg::field::RTPHeader field.

#pragma once

#include <cstdint>
#include "oac_msg/field/RTPExtensionCommon.h"
#include "oac_msg/field/RTPFlagsCommon.h"

namespace oac_msg
{

namespace field
{

/// @brief Scope for all the common definitions of the member fields of
///     @ref oac_msg::field::RTPHeader field.
struct RTPHeaderMembersCommon
{
    /// @brief Common definitions of the member fields of
    ///     @ref oac_msg::field::RTPHeaderMembers::Flags field.
    using FlagsMembersCommon = oac_msg::field::RTPFlagsMembersCommon;

    /// @brief Common types and functions for
    ///     @ref oac_msg::field::RTPHeaderMembers::Flags field.
    struct FlagsCommon : public oac_msg::field::RTPFlagsCommon
    {
        /// @brief Name of the @ref oac_msg::field::RTPHeaderMembers::Flags field.
        static const char* name()
        {
            return "flags";
        }
    };

    /// @brief Common types and functions for
    ///     @ref oac_msg::field::RTPHeaderMembers::Sequence_number field.
    struct Sequence_numberCommon
    {
        /// @brief Re-definition of the value type used by
        ///     oac_msg::field::RTPHeaderMembers::Sequence_number field.
        using ValueType = std::uint16_t;

        /// @brief Name of the @ref oac_msg::field::RTPHeaderMembers::Sequence_number field.
        static const char* name()
        {
            return "sequence_number";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Common types and functions for
    ///     @ref oac_msg::field::RTPHeaderMembers::Timestamp field.
    struct TimestampCommon
    {
        /// @brief Re-definition of the value type used by
        ///     oac_msg::field::RTPHeaderMembers::Timestamp field.
        using ValueType = std::uint32_t;

        /// @brief Name of the @ref oac_msg::field::RTPHeaderMembers::Timestamp field.
        static const char* name()
        {
            return "timestamp";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Common types and functions for
    ///     @ref oac_msg::field::RTPHeaderMembers::Ssrc field.
    struct SsrcCommon
    {
        /// @brief Re-definition of the value type used by
        ///     oac_msg::field::RTPHeaderMembers::Ssrc field.
        using ValueType = std::uint32_t;

        /// @brief Name of the @ref oac_msg::field::RTPHeaderMembers::Ssrc field.
        static const char* name()
        {
            return "ssrc";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Scope for all the common definitions of the member fields of
    ///     @ref oac_msg::field::RTPHeaderMembers::Opt_extension field.
    struct Opt_extensionMembersCommon
    {
        /// @brief Common definitions of the member fields of
        ///     @ref oac_msg::field::RTPHeaderMembers::Opt_extensionMembers::RTPExtension field.
        using RTPExtensionMembersCommon = oac_msg::field::RTPExtensionMembersCommon;

        /// @brief Common types and functions for
        ///     @ref oac_msg::field::RTPHeaderMembers::Opt_extensionMembers::RTPExtension field.
        using RTPExtensionCommon = oac_msg::field::RTPExtensionCommon;
    };

    /// @brief Common types and functions for
    ///     @ref oac_msg::field::RTPHeaderMembers::Opt_extension field.
    struct Opt_extensionCommon
    {
        /// @brief Name of the @ref oac_msg::field::RTPHeaderMembers::Opt_extension field.
        static const char* name()
        {
            return "opt_extension";
        }
    };
};

/// @brief Common types and functions for
///     @ref oac_msg::field::RTPHeader field.
struct RTPHeaderCommon
{
    /// @brief Name of the @ref oac_msg::field::RTPHeader field.
    static const char* name()
    {
        return "RTPHeader";
    }
};

} // namespace field

} // namespace oac_msg
