// Generated by commsdsl2comms v5.0.1

/// @file
/// @brief Contains definition of the ClientInputMessages messages bundle.

#pragma once

#include <tuple>
#include "oac_msg/message/DNTPMessage.h"
#include "oac_msg/message/RTPMessage.h"
#include "oac_msg/options/DefaultOptions.h"

namespace oac_msg
{

namespace input
{

/// @brief Messages of the protocol in ascending order.
/// @tparam TBase Base class of all the messages.
/// @tparam TOpt Protocol definition options.
template <typename TBase, typename TOpt = oac_msg::options::DefaultOptions>
using ClientInputMessages =
    std::tuple<
        oac_msg::message::DNTPMessage<TBase, TOpt>,
        oac_msg::message::RTPMessage<TBase, TOpt>
    >;

} // namespace input

} // namespace oac_msg
