// Generated by commsdsl2comms v5.0.1

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref oac_msg::message::DNTPMessage message and its fields.

#pragma once

#include <cstdint>
#include "oac_msg/field/TimestampCommon.h"

namespace oac_msg
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref oac_msg::message::DNTPMessage message.
/// @see oac_msg::message::DNTPMessageFields
struct DNTPMessageFieldsCommon
{
    /// @brief Common types and functions for
    ///     @ref oac_msg::message::DNTPMessageFields::Version field.
    struct VersionCommon
    {
        /// @brief Re-definition of the value type used by
        ///     oac_msg::message::DNTPMessageFields::Version field.
        using ValueType = std::uint8_t;

        /// @brief Name of the @ref oac_msg::message::DNTPMessageFields::Version field.
        static const char* name()
        {
            return "version";
        }

        /// @brief Compile time detection of special values presence.
        static constexpr bool hasSpecials()
        {
            return false;
        }
    };

    /// @brief Common definitions of the member fields of
    ///     @ref oac_msg::message::DNTPMessageFields::Originate_timestamp field.
    using Originate_timestampMembersCommon = oac_msg::field::TimestampMembersCommon;

    /// @brief Common types and functions for
    ///     @ref oac_msg::message::DNTPMessageFields::Originate_timestamp field.
    struct Originate_timestampCommon : public oac_msg::field::TimestampCommon
    {
        /// @brief Name of the @ref oac_msg::message::DNTPMessageFields::Originate_timestamp field.
        static const char* name()
        {
            return "originate_timestamp";
        }
    };

    /// @brief Common definitions of the member fields of
    ///     @ref oac_msg::message::DNTPMessageFields::Receive_timestamp field.
    using Receive_timestampMembersCommon = oac_msg::field::TimestampMembersCommon;

    /// @brief Common types and functions for
    ///     @ref oac_msg::message::DNTPMessageFields::Receive_timestamp field.
    struct Receive_timestampCommon : public oac_msg::field::TimestampCommon
    {
        /// @brief Name of the @ref oac_msg::message::DNTPMessageFields::Receive_timestamp field.
        static const char* name()
        {
            return "receive_timestamp";
        }
    };

    /// @brief Common definitions of the member fields of
    ///     @ref oac_msg::message::DNTPMessageFields::Transmit_timestamp field.
    using Transmit_timestampMembersCommon = oac_msg::field::TimestampMembersCommon;

    /// @brief Common types and functions for
    ///     @ref oac_msg::message::DNTPMessageFields::Transmit_timestamp field.
    struct Transmit_timestampCommon : public oac_msg::field::TimestampCommon
    {
        /// @brief Name of the @ref oac_msg::message::DNTPMessageFields::Transmit_timestamp field.
        static const char* name()
        {
            return "transmit_timestamp";
        }
    };
};

/// @brief Common types and functions of 
///     @ref oac_msg::message::DNTPMessage message.
struct DNTPMessageCommon
{
    /// @brief Name of the @ref oac_msg::message::DNTPMessage message.
    static const char* name()
    {
        return "DNTPMessage";
    }
};

} // namespace message

} // namespace oac_msg
