// Generated by commsdsl2comms v5.0.1

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref oac_msg::message::RTPMessage message and its fields.

#pragma once

#include <cstdint>
#include "oac_msg/field/RTPHeaderCommon.h"

namespace oac_msg
{

namespace message
{

/// @brief Common types and functions for fields of 
///     @ref oac_msg::message::RTPMessage message.
/// @see oac_msg::message::RTPMessageFields
struct RTPMessageFieldsCommon
{
    /// @brief Common definitions of the member fields of
    ///     @ref oac_msg::message::RTPMessageFields::Header field.
    using HeaderMembersCommon = oac_msg::field::RTPHeaderMembersCommon;

    /// @brief Common types and functions for
    ///     @ref oac_msg::message::RTPMessageFields::Header field.
    struct HeaderCommon : public oac_msg::field::RTPHeaderCommon
    {
        /// @brief Name of the @ref oac_msg::message::RTPMessageFields::Header field.
        static const char* name()
        {
            return "header";
        }
    };

    /// @brief Scope for all the common definitions of the member fields of
    ///     @ref oac_msg::message::RTPMessageFields::Content field.
    struct ContentMembersCommon
    {
        /// @brief Common types and functions for
        ///     @ref oac_msg::message::RTPMessageFields::ContentMembers::Element field.
        struct ElementCommon
        {
            /// @brief Re-definition of the value type used by
            ///     oac_msg::message::RTPMessageFields::ContentMembers::Element field.
            using ValueType = std::int16_t;

            /// @brief Name of the @ref oac_msg::message::RTPMessageFields::ContentMembers::Element field.
            static const char* name()
            {
                return "element";
            }

            /// @brief Compile time detection of special values presence.
            static constexpr bool hasSpecials()
            {
                return false;
            }
        };
    };

    /// @brief Common types and functions for
    ///     @ref oac_msg::message::RTPMessageFields::Content field.
    struct ContentCommon
    {
        /// @brief Name of the @ref oac_msg::message::RTPMessageFields::Content field.
        static const char* name()
        {
            return "content";
        }
    };
};

/// @brief Common types and functions of 
///     @ref oac_msg::message::RTPMessage message.
struct RTPMessageCommon
{
    /// @brief Name of the @ref oac_msg::message::RTPMessage message.
    static const char* name()
    {
        return "RTPMessage";
    }
};

} // namespace message

} // namespace oac_msg
