// Generated by commsdsl2comms v5.0.1

/// @file
/// @brief Contains common template parameters independent functionality of
///    @ref dntp_msg::MessageInterface interface fields.

#pragma once

#include "dntp_msg/field/MessageCommon.h"

namespace dntp_msg
{

/// @brief Common types and functions for fields of 
///     @ref dntp_msg::MessageInterface interface.
/// @see dntp_msg::MessageInterfaceFields
struct MessageInterfaceFieldsCommon
{
    /// @brief Common definitions of the member fields of
    ///     @ref dntp_msg::MessageInterfaceFields::Message field.
    using MessageMembersCommon = dntp_msg::field::MessageMembersCommon;

    /// @brief Common types and functions for
    ///     @ref dntp_msg::MessageInterfaceFields::Message field.
    using MessageCommon = dntp_msg::field::MessageCommon;
};
} // namespace dntp_msg
