// Generated by commsdsl2comms v5.0.1

/// @file
/// @brief Contains definition of <b>"MessageInterface"</b> interface class.

#pragma once

#include <tuple>
#include "comms/Message.h"
#include "comms/options.h"
#include "dntp_msg/MessageInterfaceCommon.h"
#include "dntp_msg/MsgId.h"
#include "dntp_msg/field/FieldBase.h"
#include "dntp_msg/field/Message.h"

namespace dntp_msg
{

/// @brief Extra transport fields of @ref MessageInterface interface class.
/// @see @ref MessageInterface
/// @headerfile dntp_msg/MessageInterface.h
struct MessageInterfaceFields
{
    /// @brief Definition of <b>"Message"</b> field.
    using Message =
        dntp_msg::field::Message<
            dntp_msg::options::DefaultOptions
        >;

    /// @brief All the fields bundled in std::tuple.
    using All = std::tuple<
        Message
    >;
};

/// @brief Definition of <b>"MessageInterface"</b> common interface class.
/// @tparam TOpt Interface definition options
/// @headerfile dntp_msg/MessageInterface.h
template <typename... TOpt>
class MessageInterface : public
    comms::Message<
        TOpt...,
        comms::option::def::BigEndian,
        comms::option::def::MsgIdType<dntp_msg::MsgId>,
        comms::option::def::ExtraTransportFields<MessageInterfaceFields::All>
    >
{
    using Base =
        comms::Message<
            TOpt...,
            comms::option::def::BigEndian,
            comms::option::def::MsgIdType<dntp_msg::MsgId>,
            comms::option::def::ExtraTransportFields<MessageInterfaceFields::All>
        >;
public:
    /// @brief Allow access to extra transport fields.
    /// @details See definition of @b COMMS_MSG_TRANSPORT_FIELDS_NAMES macro
    ///     related to @b comms::Message class from COMMS library
    ///     for details.
    ///
    ///     The generated values, types and functions are:
    ///     @li @b TransportFieldIdx_message index, @b TransportField_message type
    ///         and @b transportField_message() access fuction for @ref MessageInterfaceFields::Message field.
    COMMS_MSG_TRANSPORT_FIELDS_NAMES(
        message
    );
};

} // namespace dntp_msg
