// Generated by commsdsl2comms v5.0.1

/// @file
/// @brief Contains definition of message ids enumeration.

#pragma once

#include <cstdint>
#include "dntp_msg/Version.h"

namespace dntp_msg
{
/// @brief Message ids enumeration.
enum MsgId : unsigned
{
};

} // namespace dntp_msg
