// Generated by commsdsl2comms v5.0.1

/// @file
/// @brief Contains definition of the ClientInputMessages messages bundle.

#pragma once

#include <tuple>
#include "dntp_msg/options/DefaultOptions.h"

namespace dntp_msg
{

namespace input
{

/// @brief Messages of the protocol in ascending order.
/// @tparam TBase Base class of all the messages.
/// @tparam TOpt Protocol definition options.
template <typename TBase, typename TOpt = dntp_msg::options::DefaultOptions>
using ClientInputMessages =
    std::tuple<
    >;

} // namespace input

} // namespace dntp_msg
