// Generated by commsdsl2comms v5.0.1

/// @file
/// @brief Contains definition of message ids enumeration.

#pragma once

#include <cstdint>
#include "oac_msg/Version.h"

namespace oac_msg
{
/// @brief Message ids enumeration.
enum MsgId : unsigned
{
    MsgId_DNTPMessage = 1U,
    MsgId_RTPMessage = 2U
};

} // namespace oac_msg
