// Generated by commsdsl2comms v5.0.1

/// @file
/// @brief Contains protocol version definition.

#pragma once

#include "comms/version.h"

/// @brief Version of the protocol specification.
#define OAC_MSG_SPEC_VERSION (0U)

namespace oac_msg
{

/// @brief Version of the protocol specification.
inline constexpr unsigned specVersion()
{
    return OAC_MSG_SPEC_VERSION;
}

} // namespace oac_msg

// Generated compile time check for minimal supported version of the COMMS library
static_assert(COMMS_MAKE_VERSION(5, 0, 1) <= comms::version(),
    "The version of COMMS library is too old");
